jovotech/jovo-cli

README.md

Fixed the example links and added one for the third example.

Fix template links

---

commands/build.js
commands/deploy.js
commands/get.js
commands/init.js
commands/run.js

`jovo help <command>` did not display anything for the `build`, `deploy`, `init` command.
`jovo help <command>` resulted in an invalid command error on `get` and `run`.
Issue: [#39](https://github.com/jovotech/jovo-cli/issues/39)

🐛 fixes help not displaying commands details 

---

helper/alexaInteractionModel.js

Just one I noticed while using the cli
- [ x] Bug fix (non-breaking change which fixes an issue)
- [ x] My code follows the code style of this project
- [ x] My change requires a change to the documentation (sort of, it's an error msg)

[Typo] Fixed error message 'at leas' to 'atleast'

---

commands/build.js
commands/deploy.js
commands/get.js
commands/init.js
commands/new.js
commands/run.js
test/testBuild.js
test/testDeploy.js
test/testInit.js
test/testNew.js
test/testRun.js

This resolves issue #62. I've also enhanced the unit tests to catch this issue as well, simplifying them a bit in the process.

Addressed issue where vorpal actions weren't signaling done.

---

.gitignore
.travis.yml
package-lock.json

Some small Travis CI build improvements. Got rid of unnecessary installs and switched to the faster `npm ci` (along with checking in the requisite package-lock.json), as well as switching the builds from running on Node.js 7 (EOL'd) to Node.js 8 (LTS) and 10 (Latest).

Speeding up Travis build and switching from Node 7 to 8/10

---

helper/dialogFlowAgent.js

affects jovo build -p googleAction
changes to bugfix made in https://github.com/jovotech/jovo-cli/issues/55
Accents are no longer removed when building a dialogflow model.
Fixes a lot of issues in French (and probably other languages as well)

:bug: accents in synonyms

---

jovo-cli/utils/Utils.ts

Fix typo: informatoin -> information

---

packages/jovo-cli-platform-alexa/src/Platform.ts

Added additional default values for skill.json so that all required values are present to create a beta test.

#87 Add additional default values to skill.json 

---

jovo-cli/package.json
jovo-cli/src/commands/update.ts
jovo-cli/src/utils/JovoCliRenderer.ts
jovo-cli/test/deploy.test.ts
package-lock.json
package.json
packages/jovo-cli-core/package.json
packages/jovo-cli-deploy-lambda/package.json
packages/jovo-cli-platform-alexa/package.json
packages/jovo-cli-platform-google/package.json
packages/jovo-cli-platform-google/src/DialogflowUtil.ts
packages/jovo-webhook-connector/package.json
packages/jovo-webhook-connector/test/SocketRedirect.test.ts

Add missing V3 version bumps

---

jovo-cli/src/commands/deploy.ts
jovo-cli/src/commands/get.ts
jovo-cli/src/commands/new.ts

♻️ Remove default value for deploy.ts

---

jovo-cli/bin/run
jovo-cli/package.json
jovo-cli/src/index.ts
package-lock.json

🚑 Require .env values

---

packages/jovo-cli-platform-alexa/src/Ask.ts

💩 Add Warning for ask-cli@v2

---

jovo-cli/test/deploy.test.ts
packages/jovo-cli-platform-alexa/src/Ask.ts
packages/jovo-cli-platform-alexa/src/Platform.ts

🐛 Suppress ask-cli Error Bug

---

packages/jovo-cli-platform-alexa/src/Platform.ts

♻️ Fix Error Log for Deprecated Folder Structure

---

jovo-cli/src/commands/build.ts
jovo-cli/src/commands/convert.ts
jovo-cli/src/commands/deploy.ts
jovo-cli/src/commands/get.ts
jovo-cli/src/commands/load.ts
jovo-cli/src/commands/new.ts
jovo-cli/src/commands/run.ts
jovo-cli/src/commands/update.ts
jovo-cli/src/utils/index.ts
packages/jovo-cli-platform-alexa/src/Platform.ts
packages/jovo-cli-platform-alexa/src/utils/index.ts

Parses more ASK CLI error messages for clarity.

🥅 Enhance verbose error messages

---

jovo-cli/src/utils/Tasks.ts
jovo-cli/test/load.test.ts
packages/jovo-cli-core/src/Project.ts
packages/jovo-cli-platform-alexa/src/Platform.ts
packages/jovo-cli-platform-google/src/Platform.ts

This change introduces resolving the local webhook endpoint ${JOVO_WEBHOOK_URL} for Skill Events.

🐛 Resolve JOVO_WEBHOOK_URL for Skill Events

---

packages/jovo-cli-platform-alexa/src/Platform.ts

🐛 Fix logs for undefined ask profile

---

jovo-cli/src/commands/update.ts
jovo-cli/src/utils/Interfaces.ts
jovo-cli/src/utils/index.ts

Fix `jovo update` mentioned in the community forum.
https://community.jovo.tech/t/jovo-update-moves-dev-dependencies-into-prod-dependencies/1140/2

:bug: Should fix jovo update for devDependencies

---

jovo-cli/src/hooks/VersionHook.ts

Fixes dependencies version view on `jovo -v`

:bug: Fix dependecies version view

---

jovo-cli-platforms/jovo-cli-platform-spokestack/src/Platform.ts

🐛 Fix deployment issues with Spokestack for skipping locales

---

jovo-cli-platforms/jovo-cli-platform-google/src/Platform.ts

Just some renames in the google platform.

rename some stuff in google platform

---

jovo-cli/src/commands/build.ts
jovo-cli/src/commands/deploy.ts
jovo-cli/src/commands/get.ts
jovo-cli/src/commands/new.ts
jovo-cli/src/utils/Platforms.ts
jovo-cli/src/utils/Tasks.ts

When selecting `googleAction` as a platform, the correct tasks will be selected depending on the `project.js` configuration. This however has to take staging into account, which wasn't the case before.

🐛 Solve staging bug for Google Conversational Actions

---

jovo-cli-core/package-lock.json
jovo-cli-platforms/jovo-cli-platform-google-ca/src/Platform.ts
jovo-cli-platforms/jovo-cli-platform-google-ca/src/utils/Interfaces.ts
jovo-cli-platforms/jovo-cli-platform-google-ca/src/utils/index.ts
jovo-cli/package-lock.json
jovo-cli/test/Helpers.ts
jovo-cli/test/build.test.ts
jovo-cli/test/deploy.test.ts

✨ Add support for Conversational Action Scenes

---

jovo-cli-platforms/jovo-cli-platform-google-ca/src/Platform.ts
jovo-cli-platforms/jovo-cli-platform-google-ca/src/utils/Interfaces.ts

✨🐛 Merge config actions, solve staging problem

---

jovo-cli-platforms/jovo-cli-platform-google-ca/src/Platform.ts
jovo-cli-platforms/jovo-cli-platform-google-ca/src/utils/Interfaces.ts
jovo-cli/src/utils/Platforms.ts
jovo-cli/src/utils/Validators.ts

🐛 Fix minor issues

---

jovo-cli-platforms/jovo-cli-platform-google-ca/src/Platform.ts

🐛 Fix bug for omitted project settings

---

jovo-cli-platforms/jovo-cli-platform-google-ca/src/Platform.ts
jovo-cli-platforms/jovo-cli-platform-google-ca/src/utils/index.ts
jovo-cli/src/commands/build.ts
jovo-cli/src/utils/Prompts.ts

This PR addresses the following features/issues:
With the support of Conversational Actions, Dialogflow is not the default nlu for Google Actions anymore, hence some prompts need to be adjusted.
Setting the endpoint via `googleAction.endpoint` in the `project.js` is now supported.

🐛 Address various features/issues

---

cli/package-lock.json
cli/package.json
commands/command-build/package-lock.json
commands/command-build/package.json
commands/command-deploy/package-lock.json
commands/command-deploy/package.json
commands/command-get/package-lock.json
commands/command-get/package.json
commands/command-new/package-lock.json
commands/command-new/package.json
commands/command-run/package-lock.json
commands/command-run/package.json
core/package-lock.json
core/package.json
lerna.json
package.json

🔖 Publish 

---

cli/package.json

🐛 Change location of Oclif hooks

---

commands/command-new/src/utils/index.ts

🚚 Rename template

---

cli/package.json

⬆️ Set @jovotech/clic-ore as dependency

---

commands/command-run/src/commands/run.ts
core/src/Project.ts

🔨 Update jovo run process

---

bin/postpublish
cli/package-lock.json
cli/package.json

When automatically generating the changelog, the postpublish script looks for the status of the latest workflow and fetches the changes to the local repository upon success. This PR fixes a bug with `git merge`.

🐛 Fix merging on postpublish

---

core/src/Config.ts
core/test/Config.test.ts

Closes jovotech/jovo-framework/issues/1035

:fire: Remove unneeded instance check for plugins

---

commands/command-run/src/commands/run.ts

Fix piping process.stdin to child process
